[[CURRENCIES]]
code = "MYTOKEN"
issuer = "GC7HNVZC4YPCGZXJWKKE6XMLCX6RCEOQUEUEGWCUFQ64JJF4RESIPOXK"
name = "Saadu"
desc = "Wannan token din gwaji ne don koyo a Pi Testnet"
image = "https://i.imgur.com/placeholder.png"
